apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 503237308475.dkr.ecr.us-east-1.amazonaws.com/team4-ecr
  newName: 503237308475.dkr.ecr.us-east-1.amazonaws.com/team4-ecr
  newTag: ee21b3fc
resources:
- ../../base
patchesStrategicMerge:
- web-deploy-patch.yaml
- web-service-patch.yaml
