apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: web-deploy
  template:
    metadata:
      labels:
        app: web-deploy
